name: 'Terraform GitHub Actions'
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master

      - name: 'terraform format'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.14.11
          tf_actions_subcommand: 'fmt'
        env:
          AWS_DEFAULT_REGION: eu-central-1
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 'terraform init'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.14.11
          tf_actions_subcommand: 'init'
        env:
          AWS_DEFAULT_REGION: eu-central-1
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 'terraform validate'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.14.11
          tf_actions_subcommand: 'validate'
        env:
          AWS_DEFAULT_REGION: eu-central-1
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # - name: 'terraform plan'
      #   uses: hashicorp/terraform-github-actions@master
      #   with:
      #     tf_actions_version: 0.14.11
      #     tf_actions_subcommand: 'plan'
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
